import { placeholderImage } from "./placeholders.js";

export const demoProperties = [
  {
    id: 1,
    slug: "skyline-residences",
    name: "Skyline Residences",
    location: "Satellite, Ahmedabad",
    city: "Ahmedabad",
    locality: "Satellite",
    listing_type: "buy",
    property_type: ["Residential", "Apartment"],
    bhk: "3 BHK",
    bhk_min: 3,
    bhk_max: 3,
    carpet_area: 182,
    price: 16500000,
    price_type: "starting_from",
    price_per_sqft: 8450,
    developed_by: "Northline Developers",
    rera_no: "DEMO-RERA-1024",
    image_url: placeholderImage("Skyline Residences", 1200, 800),
    amenities: ["Clubhouse", "Gym", "Garden", "Security", "Parking"],
    floor_space_pricing: [{ configuration: "3 BHK", carpet_area: "182 sq.yard", price: "Starting from ₹1.65 Cr" }],
    google_drive_url: "#",
    google_map_location: "#",
    about_property: "A refined apartment community with efficient layouts, generous balconies, and everyday conveniences close to schools, offices, and retail streets.",
    about_builder_company: "Northline Developers is a fictional demo developer focused on well-planned urban housing and dependable handovers.",
    about_location: "Satellite offers strong connectivity, established social infrastructure, and a balanced residential atmosphere.",
    explore_neighbourhood: "Nearby conveniences include cafes, supermarkets, hospitals, parks, and arterial roads for easy cross-city travel.",
    is_featured: true,
    is_published: true,
    created_at: "2026-06-12T09:00:00.000Z",
  },
  {
    id: 2,
    slug: "willow-court-villas",
    name: "Willow Court Villas",
    location: "Shilaj, Ahmedabad",
    city: "Ahmedabad",
    locality: "Shilaj",
    listing_type: "buy",
    property_type: ["Residential", "Villa"],
    bhk: "4 BHK",
    bhk_min: 4,
    bhk_max: 4,
    carpet_area: 310,
    price: 32500000,
    price_type: "exact",
    price_per_sqft: 9800,
    developed_by: "Evergreen Habitat",
    rera_no: "DEMO-RERA-2048",
    image_url: placeholderImage("Willow Court Villas", 1200, 800),
    amenities: ["Private Garden", "Parking", "Security", "Community Lounge"],
    floor_space_pricing: [{ configuration: "4 BHK Villa", carpet_area: "310 sq.yard", price: "₹3.25 Cr" }],
    google_drive_url: "#",
    google_map_location: "#",
    about_property: "A low-density villa address designed for families who want privacy, open space, and polished finishes in a calm neighbourhood.",
    about_builder_company: "Evergreen Habitat is a fictional builder profile created for this portfolio demo.",
    about_location: "Shilaj is known for leafy residential pockets, good road access, and growing lifestyle infrastructure.",
    explore_neighbourhood: "International schools, restaurants, wellness centres, and weekend recreation options are within convenient reach.",
    is_featured: true,
    is_published: true,
    created_at: "2026-06-08T09:00:00.000Z",
  },
  {
    id: 3,
    slug: "metro-edge-offices",
    name: "Metro Edge Offices",
    location: "Prahlad Nagar, Ahmedabad",
    city: "Ahmedabad",
    locality: "Prahlad Nagar",
    listing_type: "commercial",
    property_type: ["Commercial", "Office"],
    bhk: "",
    bhk_min: null,
    bhk_max: null,
    carpet_area: 145,
    price: 9200000,
    price_type: "starting_from",
    price_per_sqft: 11200,
    developed_by: "Civic Square Realty",
    rera_no: "DEMO-RERA-3096",
    image_url: placeholderImage("Metro Edge Offices", 1200, 800),
    amenities: ["Reception", "Elevators", "Parking", "Power Backup"],
    floor_space_pricing: [{ configuration: "Office Suite", carpet_area: "145 sq.yard", price: "Starting from ₹92 L" }],
    google_drive_url: "#",
    google_map_location: "#",
    about_property: "Flexible office suites for growing teams, with a professional arrival experience and practical floor plates.",
    about_builder_company: "Civic Square Realty is a fictional commercial real estate brand used for demo content.",
    about_location: "Prahlad Nagar remains a sought-after business corridor with strong hospitality and dining options.",
    explore_neighbourhood: "Banks, business hotels, cafes, and rapid access routes support a productive workday.",
    is_featured: true,
    is_published: true,
    created_at: "2026-05-28T09:00:00.000Z",
  },
  {
    id: 4,
    slug: "parkview-heights",
    name: "Parkview Heights",
    location: "Vastrapur, Ahmedabad",
    city: "Ahmedabad",
    locality: "Vastrapur",
    listing_type: "rent",
    property_type: ["Residential", "Apartment"],
    bhk: "2 BHK",
    bhk_min: 2,
    bhk_max: 2,
    carpet_area: 118,
    price: 42000,
    price_type: "exact",
    price_per_sqft: null,
    developed_by: "Demo Asset Management",
    rera_no: "",
    image_url: placeholderImage("Parkview Heights", 1200, 800),
    amenities: ["Furnished", "Parking", "Security", "Lift"],
    floor_space_pricing: [{ configuration: "2 BHK", carpet_area: "118 sq.yard", price: "₹42,000/month" }],
    google_drive_url: "#",
    google_map_location: "#",
    about_property: "A move-in-ready rental apartment with functional furniture, natural light, and quick access to daily conveniences.",
    about_builder_company: "Managed by a fictional leasing team for this demo website.",
    about_location: "Vastrapur combines established residential streets with lakeside leisure and strong city connectivity.",
    explore_neighbourhood: "Malls, education hubs, restaurants, and public transport connections are close by.",
    is_featured: false,
    is_published: true,
    created_at: "2026-05-20T09:00:00.000Z",
  },
];
